### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by gaborcsardi** [bionode/github-project-public#6]
This looks like an awesome project. Do you have any tip what this failure could be?
```
node projects.js r-hub
```

```
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: stream.push() after EOF
    at readableAddChunk (/Users/gaborcsardi/works/github-project-public/node_modules/tool-stream/node_modules/readable-stream/lib/_stream_readable.js:168:15)
    at Transform.Readable.push (/Users/gaborcsardi/works/github-project-public/node_modules/tool-stream/node_modules/readable-stream/lib/_stream_readable.js:149:10)
    at Transform.push (/Users/gaborcsardi/works/github-project-public/node_modules/tool-stream/node_modules/readable-stream/lib/_stream_transform.js:145:32)
    at Transform.extract [as _transform] (/Users/gaborcsardi/works/github-project-public/node_modules/tool-stream/lib/tool-stream.js:168:10)
    at Transform._read (/Users/gaborcsardi/works/github-project-public/node_modules/tool-stream/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at Transform._write (/Users/gaborcsardi/works/github-project-public/node_modules/tool-stream/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/Users/gaborcsardi/works/github-project-public/node_modules/tool-stream/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/Users/gaborcsardi/works/github-project-public/node_modules/tool-stream/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at Transform.Writable.write (/Users/gaborcsardi/works/github-project-public/node_modules/tool-stream/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at write (/Users/gaborcsardi/works/github-project-public/node_modules/tool-stream/node_modules/readable-stream/lib/_stream_readable.js:623:24)
```

**Comment by IsmailM** [comment]
Hey,

I've just checked and the script is working fine with the bionode organisation (running with node v8.9.4 and v7.10.1). Can you retry with one of these Node versions?

Does the script start to output anything or does the error appear straight away?

cc @bmpvieira

**Comment by gaborcsardi** [comment]
I am using node v8.9.4, so it must be sg else. Do you assume a certain set of project columns? 

The script starts to download the data just fine, but then it stumbles on a record. This is the one that generates the error:

```
{
  "url": "https://api.github.com/repos/r-hub/rhub-frontend/issues/15",
  "repository_url": "https://api.github.com/repos/r-hub/rhub-frontend",
  "labels_url": "https://api.github.com/repos/r-hub/rhub-frontend/issues/15/labels{/name}",
  "comments_url": "https://api.github.com/repos/r-hub/rhub-frontend/issues/15/comments",
  "events_url": "https://api.github.com/repos/r-hub/rhub-frontend/issues/15/events",
  "html_url": "https://github.com/r-hub/rhub-frontend/issues/15",
  "id": 185543372,
  "number": 15,
  "title": "Unexpected token u",
  "user": {
    "login": "DavisBrian",
    "id": 7526919,
    "avatar_url": "https://avatars2.githubusercontent.com/u/7526919?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/DavisBrian",
    "html_url": "https://github.com/DavisBrian",
    "followers_url": "https://api.github.com/users/DavisBrian/followers",
    "following_url": "https://api.github.com/users/DavisBrian/following{/other_user}",
    "gists_url": "https://api.github.com/users/DavisBrian/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/DavisBrian/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/DavisBrian/subscriptions",
    "organizations_url": "https://api.github.com/users/DavisBrian/orgs",
    "repos_url": "https://api.github.com/users/DavisBrian/repos",
    "events_url": "https://api.github.com/users/DavisBrian/events{/privacy}",
    "received_events_url": "https://api.github.com/users/DavisBrian/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [
    {
      "id": 846627104,
      "url": "https://api.github.com/repos/r-hub/rhub-frontend/labels/stability",
      "name": "stability",
      "color": "77eaca",
      "default": false
    },
    {
      "id": 846626976,
      "url": "https://api.github.com/repos/r-hub/rhub-frontend/labels/ui-design",
      "name": "ui-design",
      "color": "0d1672",
      "default": false
    },
    {
      "id": 846626819,
      "url": "https://api.github.com/repos/r-hub/rhub-frontend/labels/user%20request",
      "name": "user request",
      "color": "72ea82",
      "default": false
    }
  ],
  "state": "open",
  "locked": false,
  "assignee": null,
  "assignees": [],
  "milestone": null,
  "comments": 5,
  "created_at": "2016-10-27T00:16:55Z",
  "updated_at": "2018-02-23T23:27:30Z",
  "closed_at": null,
  "author_association": "NONE",
  "body": "Anytime I try to upload a package for test and choose to verify via github I get \"Unexpected token u\" webpage.  Works fine if I verify via email.  \n",
  "closed_by": null,
  "column_url": "https://api.github.com/projects/columns/2230074",
  "column_name": "Backlog"
}
```

The organization has no restrictions for apps (although I not sure if this is needed):
> Policy: No restrictions 
> All applications authorized by organization members have access to r-hub’s data.

See the screenshot below for the scopes I have in the token, that should be fine I think.

Am I missing anything? Any tips are welcome!

<img width="717" alt="screen shot 2018-03-06 at 9 38 14 am" src="https://user-images.githubusercontent.com/660288/37024991-66fceea8-2122-11e8-957e-8e6c613db09a.png">

**Comment by gaborcsardi** [comment]
Actually, if I run it again, it stop at a different issue.
